change to .bashrc

diff --git a/.github/workflows/scrape-and-build.yaml b/.github/workflows/scrape-and-build.yaml
--- a/.github/workflows/scrape-and-build.yaml
+++ b/.github/workflows/scrape-and-build.yaml
@@ -58,7 +58,7 @@ jobs:
     steps:
       
       - name: Set up logging
-        run: "echo 'exec 2> >(tee -a /tmp/error.log >&2) > >(tee -a /tmp/out.log)' >> ~/.profile"
+        run: "echo 'exec 2> >(tee -a /tmp/error.log >&2) > >(tee -a /tmp/out.log)' >> ~/.bashrc"
 
       - uses: actions/checkout@v3
         with:
